#!/usr/bin/env bash
#Installs nginx on a server and configures it to have a custom http response header
shellcheck -e SC2154 0-custom_http_response_header
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chmod 777 /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo chmod 644 /var/www/html/index.nginx-debian.html
new_conf="server_name _;\n\trewrite ^/redirect_me/$ http://www.google.com permanent;"
sudo chmod 777 /etc/nginx/sites-enabled/default
sudo sed -i "s@server_name\ _;@${new_conf}@g" /etc/nginx/sites-enabled/default
sudo sed 's/server_name _;/server_name _;\n\tadd_header\tX-Served-By\t12421-web-02;/' /etc/nginx/sites-enabled/default
sudo chmod 644 /etc/nginx/sites-enabled/default
sudo service nginx start
